### ISSUE TITLE
When using the ScriptEngine to execute Frege, bindings are not visible

### ISSUE THREAD

**Issue by renatoathaydes** [Frege/frege-interpreter#33]
I am using the following Java code, approximately, to run Frege scripts:

```java
ScriptEngine scriptEngine = new ScriptEngineManager().getEngineByName( "frege" );

Bindings bindings = scriptEngine.getBindings( ScriptContext.ENGINE_SCOPE );
bindings.put( "out", out );
bindings.put( "err", err );
bindings.put( "ctx", bundleContext );

@Nullable Object result = scriptEngine.eval( script );
```

The bindings variables, `out`, `err` and `ctx` do not seem to be available in the script, as they should.

I get this error when I try to access `out`, for example:

```
frege.runtime.Undefined: [E <console>.fr:5: can't resolve `out`, did you mean `sum` perhaps?]
```

**Comment by mmhelloworld** [comment]
Hi,

Two things:

1. The necessary mechanism to make bindings work is actually on the Frege script engine's `put` but you are actually directly modifying the `Bindings` object so it doesn't currently work with your approach. It would be nice to improve this but for now, you could do: `scriptEngine.put(...)` instead of `bindings.put`

2. For the bindings, the type must be specified and the type must be known to Frege as shown in the test [here](https://github.com/Frege/frege-interpreter/blob/master/frege-interpreter-core/src/test/java/frege/interpreter/scriptengine/FregeScriptEngineTest.java#L62) with this snippet:

```java
        frege.put("bar :: Integer", new BigInteger("12312332142343244"));
        final Object actual = frege.eval("bar + 3.big");
        final Object expected = new BigInteger("12312332142343247");
        assertEquals(expected, actual);
```

Here the type of `bar` is specified while calling `put` and the type `Integer` is the Frege equivalent of Java type `BigInteger`.

**Comment by renatoathaydes** [comment]
Alright, thanks...

I should tell you that the docs for `ScriptEngine.put` say this: `Must have the same effect as getBindings(ScriptContext.ENGINE_SCOPE).put.`. 

So Frege is not being very compliant.

I need to rebind some variables when something is reloaded in my environment, but that causes an error.

```
frege.runtime.Undefined: [E <console>.fr:16: duplicate function or pattern binding for `outRef`,
    already bound on line 7]
	at frege.prelude.PreludeBase.error(PreludeBase.java:17968)
	at frege.scriptengine.FregeScriptEngine.evalResult(FregeScriptEngine.java:1480)
	at frege.scriptengine.FregeScriptEngine$15.eval(FregeScriptEngine.java:1512)
	at frege.scriptengine.FregeScriptEngine$15.eval(FregeScriptEngine.java:1492)
	at frege.runtime.Fun1$1.eval(Fun1.java:63)
	at frege.runtime.Delayed.call(Delayed.java:200)
	at frege.runtime.Delayed.forced(Delayed.java:267)
	at frege.scriptengine.FregeScriptEngine$JFregeScriptEngine.put(FregeScriptEngine.java:786)
	at com.athaydes.osgiaas.cli.frege.FregeCommand.execute(FregeCommand.java:51)
```

Is it not possible to re-bind stuff? Is there a way to reset some bindings?

**Comment by mmhelloworld** [comment]
Ok, I have to fix few things to get the rebinding work. I will try to get both the bindings api compliant issue and the rebinding issue working hopefully in the next few hours. Thanks for reporting!

**Comment by mmhelloworld** [comment]
Hi,

Sorry, it took me more longer than I expected to fix this issue. This issue is fixed now. The implementation inconsistency with the API is also fixed. Please post here if you still find any issues with it.
